<a href="https://colab.research.google.com/github/canasep/mackprojeto3/blob/main/PROJETO_APLICADO_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### PROJETO APLICADO 3 ###

In [ ]:
### PROJETO APLICADO 3

In [1]:
!git clone https://github.com/canasep/mackprojeto3.git

Cloning into 'mackprojeto3'...
remote: Enumerating objects: 250, done.
remote: Counting objects: 100% (250/250), done.
remote: Compressing objects: 100% (163/163), done.
remote: Total 250 (delta 109), reused 158 (delta 64), pack-reused 0 (from 0)
Receiving objects: 100% (250/250), 9.30 MiB | 15.02 MiB/s, done.
Resolving deltas: 100% (109/109), done.

In [ ]:
## IMPORTAÇÃO DE DATASET

In [5]:
import pandas as pd
import zipfile
import os

dataset1_path = '/content/mackprojeto3/dataset/arquivos/amazon_music_metadata.csv.zip'
extraction_path = '/content/extracted_data'

# Criação do diretório
os.makedirs(extraction_path, exist_ok=True)

# Extração do arquivo ZIP
with zipfile.ZipFile(dataset1_path, 'r') as zip_ref:
    csv_file_name = None
    for file_info in zip_ref.infolist():
        if file_info.filename.endswith('.csv') and not file_info.filename.startswith('__MACOSX'):
            csv_file_name = file_info.filename
            zip_ref.extract(file_info.filename, extraction_path)
            break

if csv_file_name:
    extracted_csv_path = os.path.join(extraction_path, csv_file_name)
    dfcsv = pd.read_csv(extracted_csv_path)

    print(f"Dataset carregado corretamente. Shape: {dfcsv.shape}")
    display(dfcsv.head())
else:
    print(f"Erro: Arquivo CSV não foi encontrado em {dataset1_path}")

Dataset carregado corretamente. Shape: (6931, 463)

,asin,title,Accessories,Acid Jazz,Acoustic Blues,Adult Alternative,Adult Contemporary,Africa,Afro Brazilian,Afro-Cuban,...,Wall Stickers,Wall Switches,Washers,Wave Washers & Wave Springs,Wedding Music,West Coast,West Coast Blues,Western Swing,World Dance,World Music
0,5555991584,Memory of Trees,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,6308051551,Dont Drink His Blood,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,7901622466,On Fire,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,B0000000ZW,Changing Faces,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,B00000016W,Pet Sounds,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## IMPORTAÇÃO DATASET DIGITAL MUSIC JSON

In [6]:
dataset_json_path = '/content/mackprojeto3/dataset/arquivos/Digital_Music_5.json.zip'
extraction_path_json = '/content/extracted_data_json'

# Criação do diretório para extração do JSON
os.makedirs(extraction_path_json, exist_ok=True)

# Extração do arquivo JSON do ZIP
with zipfile.ZipFile(dataset_json_path, 'r') as zip_ref:
    json_file_name = None
    for file_info in zip_ref.infolist():
        # Looking for .json file and ignoring any __MACOSX files
        if file_info.filename.endswith('.json') and not file_info.filename.startswith('__MACOSX'):
            json_file_name = file_info.filename
            zip_ref.extract(file_info.filename, extraction_path_json)
            break

if json_file_name:
    extracted_json_path = os.path.join(extraction_path_json, json_file_name)
    dfjson = pd.read_json(extracted_json_path, lines=True) # Assuming it's a JSONL file

    print(f"Dataset JSON carregado corretamente. Shape: {dfjson.shape}")
    display(dfjson.head())
else:
    print(f"Erro: Arquivo JSON não foi encontrado em {dataset_json_path}")

Dataset JSON carregado corretamente. Shape: (64706, 9)

,reviewerID,asin,reviewerName,helpful,reviewText,overall,summary,unixReviewTime,reviewTime
0,A3EBHHCZO6V2A4,5555991584,"Amaranth ""music fan""","[3, 3]","It's hard to believe ""Memory of Trees"" came ou...",5,Enya's last great album,1158019200,"09 12, 2006"
1,AZPWAXJG9OJXV,5555991584,bethtexas,"[0, 0]","A clasically-styled and introverted album, Mem...",5,Enya at her most elegant,991526400,"06 3, 2001"
2,A38IRL0X2T4DPF,5555991584,bob turnley,"[2, 2]",I never thought Enya would reach the sublime h...,5,The best so far,1058140800,"07 14, 2003"
3,A22IK3I6U76GX0,5555991584,Calle,"[1, 1]",This is the third review of an irish album I w...,5,Ireland produces good music.,957312000,"05 3, 2000"
4,A1AISPOIIHTHXX,5555991584,"Cloud ""...""","[1, 1]","Enya, despite being a successful recording art...",4,4.5; music to dream to,1200528000,"01 17, 2008"

In [15]:
# Contar o número total de usuários únicos
total_unique_users = len(review_counts)

print(f"O número total de usuários únicos na base é: {total_unique_users}")

O número total de usuários únicos na base é: 5541

In [16]:
# Contar o número de reviews por reviewerID
review_counts = dfjson['reviewerID'].value_counts()

# Filtrar os usuários que deram mais de uma review
users_with_multiple_reviews = review_counts[review_counts > 5]

# Contar quantos usuários deram mais de uma review
num_users_with_multiple_reviews = len(users_with_multiple_reviews)

print(f"Número de usuários que deram mais de cinco reviews: {num_users_with_multiple_reviews}")

Número de usuários que deram mais de cinco reviews: 4022

In [17]:
# Encontrar o número máximo de revisões por um único usuário
max_reviews_per_user = review_counts.max()

print(f"O número máximo de revisões dadas por um único usuário é: {max_reviews_per_user}")

O número máximo de revisões dadas por um único usuário é: 578

In [18]:
# Contar o número de reviews por asin (música)
review_counts_by_music = dfjson['asin'].value_counts()

# Encontrar o número máximo de revisões para uma única música
max_reviews_per_music = review_counts_by_music.max()

print(f"O número máximo de revisões para uma única música é: {max_reviews_per_music}")

O número máximo de revisões para uma única música é: 272